### PR TITLE
Enabling foundations flexbox

### PR DESCRIPTION
**Pull request by sineade**
:art:

set $global-flexbox to true so we can start using flexbox.

Also had to change the order of the menu includes because with flexbox enabled the dropdown menu was staying open, this change fixes that.

### CODE REVIEW

**Comment by MathieuGilbert** [comment]
💩 Out of date with master, and there are Rubocop violations failing the Travis build.

**Comment by sineade** [comment]
oh ya! sorry meant to put the fix in for the rubocop but forgot!

**Comment by sineade** [comment]
:wave:

**Comment by MathieuGilbert** [comment]
💩  Version is already 1.0.9 in master: https://github.com/amaabca/ama_styles/blob/master/lib/ama/styles/version.rb

**Comment by MathieuGilbert** [comment]
:art: :art: :art:

**Pull request merged**
