### PR TITLE
VSTS-9877 - Redeem Reward Dollars

### PR DESCRIPTION
**Pull request by jessedoyle**
:art::elephant:

* Losslessly compress all image assets using https://kraken.io.
  This reduced net asset size by approx. 24 percent.
* Add in 1 and 2x variants of images for POS reward dollar
  redemption.
* Bump minor version.
* Remove `new_framework_defaults` file from the spec dummy app
  config. New versions of Rails no longer define these override
  methods on ActiveSupport.
* Require `foundation_rails` >= 6.4.3.0 to ensure compatibility
  with JS/CSS for foundation.
* Fix a deprecation warning about explicit references to
  `$offcanvas-size`. As we aren't referencing this variable in
  our own SCSS, it's fine to remove the definition.

## Optimization Results

screen shot 2018-04-30 at 10 03 56 am

### Admin Tasks

admintasks

### Redeem Reward Dollars

redeemrewarddollars

SEE: https://amaabca.visualstudio.com/registries_backlog/_workitems/edit/9877

### PR Review Checklist
To be completed by the person who opens the PR. Use strikethroughs for items that are not applicable in list.
- [X] I have reviewed my own PR to check syntax & logic, removed unnecessary/old code, made sure everything aligns with our style guide and BEM.
- ~[ ] I've added new components to the style guide (or have a PR in to add them).~
- [X] Any applicable version numbers have been updated.
- [X] I've tested on mobile, tablet, and desktop, as well as across all of the browsers we support.
- [X] I've proof-read all text for legibility, proper grammar, punctuation, and capitalization (titlecase).
- [X] I have written a detailed PR message explaining what is being changed and why
- [X] I’ve linked to any relevant VSTS tickets
- [X] I’ve added the appropriate review symbols to my PR - (elephant) for dev review, (art) for design

### CODE REVIEW

**Comment by jessedoyle** [comment]
:wave:

**Comment by mvandenbeuken** [comment]
📖

**Comment by mvandenbeuken** [comment]
🐘 🐘 🐘 

I'll leave the review approval for the design review.

**Comment by sineade** [comment]
:book:

**Comment by sineade** [comment]
:art: :art: :art:

**Comment by jessedoyle** [comment]
:wave:

**Comment by DaveAMA** [comment]
📖

**Comment by DaveAMA** [comment]
🎨 🎨 🎨

**Pull request merged**
