### PR TITLE
Change DE Buttons and Links (PR 1 of 3)

### PR DESCRIPTION
**Pull request by DaveAMA**
This PR adds 3 new icons which will be used on DE public in online account. 
You can see the icons here:

screen shot 2018-06-12 at 4 00 30 pm
screen shot 2018-06-12 at 4 00 23 pm

Each icon has a normal size (96) and a @2x size (192).

Icons here will be used in https://github.com/amaabca/driver_ed/pull/423 and https://github.com/amaabca/driver_ed_public/pull/201

https://amaabca.visualstudio.com/driver_education_backlog/_workitems/edit/11458

### PR Review Checklist
To be completed by the person who opens the PR. Use strikethroughs for items that are not applicable in list.
- [x] I have reviewed my own PR to check syntax & logic, removed unnecessary/old code, made sure everything aligns with our style guide and BEM.
- [x] I've added new components to the style guide (or have a PR in to add them).
- [x] Any applicable version numbers have been updated.
- [x] I've tested on mobile, tablet, and desktop, as well as across all of the browsers we support.
- [x] I've proof-read all text for legibility, proper grammar, punctuation, and capitalization (titlecase).
- [x] I have written a detailed PR message explaining what is being changed and why
- [ ] I’ve linked to any relevant VSTS tickets
- [x] I’ve added the appropriate review symbols to my PR - (elephant) for dev review, (art) for design

### CODE REVIEW

**Comment by DaveAMA** [comment]
💩 WIP

**Comment by DaveAMA** [comment]
:wave:

**Comment by sineade** [comment]
@DaveAMA I'm finding the stroke widths of the new icons seem noticeably thinner than the one's that were previously created. Could we play with thickening them a little bit?

**Comment by DaveAMA** [comment]
@sineade sure I'll take a look

**Comment by DaveAMA** [comment]
screen shot 2018-06-13 at 8 47 45 am


@sineade I've increased the icon width a touch, I've included two of ouur existing icons in the screenshot above to show how they compare. 

👋

**Comment by sineade** [comment]
:art: :art: :art: looks more consistent!

**Pull request merged**
