### PR TITLE
Fix modal

### PR DESCRIPTION
**Pull request by kaytcampbell**
:art:
Fixes scrolling issue in Road Reports https://ama-digital.myjetbrains.com/youtrack/issue/RREPORT-1116
Also changed the layers nav to be full-width on mobile and fixed the size of the logo.

It's on staging to test.

### CODE REVIEW

**Comment by sineade** [comment]
:book:

**Comment by sineade** [comment]
:art: :art: :art:

**Comment by mvandenbeuken** [comment]
📖

**Comment by mvandenbeuken** [comment]
🎨 🎨 🎨

**Pull request merged**
