### PR TITLE
VSTS-675 - Dynamic Quote

### PR DESCRIPTION
**Pull request by jessedoyle**
:art:

* Don't make the `quote-callout__content` element absolutely centered
  because it interferes with the Foundation equalizer in neighbouring
  elements.

SEE: https://amaabca.visualstudio.com/insurance_backlog/_workitems?id=675

### PR Review Checklist
To be completed by the person who opens the PR. Use strikethroughs for items that are not applicable in list.
- [X] I have reviewed my own PR to check syntax & logic, removed unnecessary/old code, made sure everything aligns with our style guide and BEM.
- ~ I've added new components to the style guide (or have a PR in to add them).~
- [X] Any applicable version numbers have been updated.
- [X] I've tested on mobile, tablet, and desktop, as well as across all of the browsers we support.
- [X] I've proof-read all text for legibility, proper grammar, punctuation, and capitalization (titlecase).
- [X] I have written a detailed PR message explaining what is being changed and why
- [X] I’ve linked to any relevant VSTS tickets
- [X] I’ve added the appropriate review symbols to my PR - (elephant) for dev review, (art) for design

### CODE REVIEW

**Comment by DaveAMA** [comment]
📖

**Comment by DaveAMA** [comment]
New:
screen shot 2018-01-30 at 3 13 49 pm

Old:
screen shot 2018-01-30 at 3 14 40 pm


it looks like this change is causing the text on the right to be no longer vertically-centred.

**Comment by DaveAMA** [comment]
💩

**Comment by jessedoyle** [comment]
@DaveAMA - You're right - we're going to revisit the approach.

For now I'm going to close this PR.

**Pull request closed without merging**
