### PR TITLE
VSTS 5971 - Add registry information request art

### PR DESCRIPTION
**Pull request by MarkBennett**
I've added the images required for the registry information request forms.

See [VSTS 5971](https://amaabca.visualstudio.com/registries_backlog/_workitems/edit/5971)

### PR Review Checklist

🐘 and 🎨

- [x] I have reviewed my own PR to check syntax & logic, removed unnecessary/old code, made sure everything aligns with our style guide and BEM.
- [x] I've added new components to the style guide (or have a PR in to add them).
- [ ] Any applicable version numbers have been updated.
- [x] I've tested on mobile, tablet, and desktop, as well as across all of the browsers we support.
- [x] I've proof-read all text for legibility, proper grammar, punctuation, and capitalization (titlecase).
- [x] I have written a detailed PR message explaining what is being changed and why
- [x] I’ve linked to any relevant VSTS tickets
- [x] I’ve added the appropriate review symbols to my PR - (elephant) for dev review, (art) for design
- [x] I've updated this branch with the latest code from master
- [ ] I've confirmed all the specs and code quality scans pass (`bundle exec rake`)

### CODE REVIEW

**Comment by MarkBennett** [comment]
I dropped that extra image @sineade. Mind taking another look? 👋

**Comment by sineade** [comment]
:art: :art: :art: so the Pr itself looks good, but i'm still unsure as to why the tests are failing here but they didn't fail locally for me? We may want to get someone else to try running them locally as well to see what's happening.

**Comment by zjullion** [comment]
:book:

**Comment by zjullion** [comment]
Alrighty, so if you take a look over at Travis, you'll see that master is now failing as well (presumably something with font awesome changed).  Kayt's branch https://github.com/amaabca/ama_styles/tree/fa5-svg is not failing, so you may need to integrate those changes to get things passing again.

**Comment by jessedoyle** [comment]
@MarkBennett - We may want to lock `font-awesome-sass` to `4.7.0`. I think that gem switched to font awesome 5 which is a breaking change.

**Comment by sineade** [comment]
@MarkBennett (upvote) @jessedoyle suggestion might just be our best bet for now, since I can't say for sure when Kayt's changes will be done.

**Comment by MarkBennett** [comment]
Can I get an updated review on this now that master has been merged? Thanks! 👋

**Comment by DaveAMA** [comment]
🎨 🎨 🎨

**Pull request merged**
