### PR TITLE
updating money bags illustration style

### PR DESCRIPTION
**Pull request by sineade**
:art:
Just updating the money bags image now that we have a more consistent icon style, and also created the different sizes necessary to do the data interchange so it looks nice on retina and non-retina screens. 
Pr's in my_ama and membership to update the images where they are being used.
https://github.com/amaabca/my_ama/pull/1298
https://github.com/amaabca/membership/pull/776

### PR Review Checklist
To be completed by the person who opens the PR. Use strikethroughs for items that are not applicable in list.
- [x] I have reviewed my own PR to check syntax & logic, removed unnecessary/old code, made sure everything aligns with our style guide and BEM.
- [x] I've added new components to the style guide (or have a PR in to add them).
- [x] Any applicable version numbers have been updated.
- [x] I've tested on mobile, tablet, and desktop, as well as across all of the browsers we support.
~~- [ ] I've proof-read all text for legibility, proper grammar, punctuation, and capitalization (titlecase).~~
- [x] I have written a detailed PR message explaining what is being changed and why
~~- [ ] I’ve linked to any relevant VSTS tickets~~
- [x] I’ve added the appropriate review symbols to my PR - (elephant) for dev review, (art) for design

### CODE REVIEW

**Comment by sineade** [comment]
:hankey:

**Comment by darkodosenovic** [comment]
:book:

**Comment by darkodosenovic** [comment]
:book:

**Comment by darkodosenovic** [comment]
🐘 🐘 🐘

**Pull request merged**
